"""empty message

Revision ID: 215dce16f122
Revises: 
Create Date: 2022-10-30 14:21:16.378751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215dce16f122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image_url', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'image_url')
    # ### end Alembic commands ###
